# Generated by Django 3.0.7 on 2020-06-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0002_auto_20200620_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dq.Patient', verbose_name='患者'),
        ),
    ]
